<?php
abstract class Animal{
    public $name;
    public $color;

    public function descride(){
        return $this->name. ' is ' . $this->color;

    }
    abstract public function makesound();
}
class Duck extends Animal{
    public function descride()
    {
        return parent::descride(); // TODO: Change the autogenerated stub
    }
    public function makesound()
    {
        // TODO: Implement makesound() method.
        return 'Quak';
    }
}
class Dog extends Animal{
    public function descride()
    {
        return parent::descride(); // TODO: Change the autogenerated stub
    }
    public function makesound()
    {
        // TODO: Implement makesound() method.
        return 'Gheu Gheu';
    }
}

$animal = new Dog();
$animal->name = 'Ben';
$animal->color = 'Yellow';
//echo $animal->descride();
echo $animal->makesound();